# Generated by Django 4.0.6 on 2022-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0006_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(blank=True, default=0, verbose_name='Preço Promocional'),
        ),
    ]
